/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TEADecrypt */

#ifndef _Included_TEADecrypt
#define _Included_TEADecrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TEADecrypt
 * Method:    runTEADecrypt
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_TEADecrypt_runTEADecrypt
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
