/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TEAEncrypt */

#ifndef _Included_TEAEncrypt
#define _Included_TEAEncrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TEAEncrypt
 * Method:    runTEAEncrypt
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_TEAEncrypt_runTEAEncrypt
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
