/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TEA_TEAEncrypt */

#ifndef _Included_TEA_TEAEncrypt
#define _Included_TEA_TEAEncrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TEA_TEAEncrypt
 * Method:    runTEAEncrypt
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_TEA_TEAEncrypt_runTEAEncrypt
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
